apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: sohotco-backend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/sohotco-backend
  newTag: 2cfdea15c5f9351635758f804db24bc901d07b63
