apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: sohotco-backend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/sohotco-backend
  newTag: f47c848992ff9e63b1d2584e92c2cafd27e9ddb3
