apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
- name: sohotco-backend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/sohotco-backend
  newTag: latest 
